// Action Types
export const SET_APP_STATE = "SET_APP_STATE";
export const CLEAR_APP_STATE = "CLEAR_APP_STATE";

export const SET_FILTER_STATE = "SET_FILTER_STATE";
export const CLEAR_FILTER_STATE = "CLEAR_FILTER_STATE";

export const REQUEST_USER_INFO = "REQUEST_USER_INFO";
export const RECEIVE_USER_INFO = "RECEIVE_USER_INFO";
export const CLEAR_USER_INFO = "CLEAR_USER_INFO";
export const STOP_FETCHING_USER_INFO = "STOP_FETCHING_USER_INFO";
